
title: Market Landscape
logo: 
description: 

show_downloads: 
google_analytics:
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: "ru"
    values:
      lang: ru

  - scope:
      path: "ja"
    values:
      lang: ja

  - scope:
      path: ""
    values:
      lang: en
